In [1]:
3/10 + 1/15

0.36666666666666664

In [2]:
3/10-1/15

0.23333333333333334

In [3]:
8%2

0

In [4]:
8/2

4.0

In [5]:
num=11
name='suresh'

In [6]:
'my number is {} and my name is {}'.format(num,name)

'my number is11 and my name is suresh'

In [7]:
s='suersh'
s[0]

's'

In [10]:
x=[1,2,[3,4]]
x[2][1]

4

In [11]:
x[2]

[3, 4]

In [12]:
x[1]

2

In [16]:
d={'key':'value','key2':123}
d['key']

'value'

In [17]:
d['key2']

123

In [18]:
d={'k1':[1,2,3]}
d['k1']

[1, 2, 3]

In [19]:
my_list=d['k1']

In [21]:
my_list[0]

1

In [26]:
{1,1,1,1,2,2,3,4,4,4}

{1, 2, 3, 4}

In [27]:
set([1,2,3,1,1,1,2,3,3,3,32,])

{1, 2, 3, 32}

In [28]:
s={1,2,3,4}
s.add(5)

In [29]:
s

{1, 2, 3, 4, 5}

In [32]:
True and False

False

In [34]:
True or  False

True

In [40]:
seq=[1,2,3,4,5]
print(seq)

[1, 2, 3, 4, 5]


In [38]:
for num in seq:
    print(num)
    print('hello')

1
hello
2
hello
3
hello
4
hello
5
hello


In [39]:
i=1
while i<5:
    print('i is: {}'.format(i))
    i=i+1

i is: 1
i is: 2
i is: 3
i is: 4


In [41]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
x=[1,2,3,4,5]
out=[]
for num in x:
    out.append(num**2)
    print(out)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]


In [45]:
print(out)

[1, 4, 9, 16, 25]


In [46]:
[num**2 for num in x]

[1, 4, 9, 16, 25]

In [47]:
out=[num**2 for num in x]

In [48]:
out


[1, 4, 9, 16, 25]

In [56]:
def my_func(name):
    print('hello '+ name) 

In [57]:
my_func('suresh')

hello suresh


In [58]:
de f square(num):
    return num**2

In [60]:
output=square(3)

In [61]:
output

9

In [64]:
square 

<function __main__.square(num)>

In [65]:
def time(var):
    return var*2

In [66]:
time(5)

10

- map

In [67]:
seq = [1,2,3,4,5]

In [69]:
list(map(time,seq))

[2, 4, 6, 8, 10]

In [70]:
x=lambda var:var*2

In [73]:
x(3)

6

In [76]:
list(map(lambda num:num*3,seq))

[3, 6, 9, 12, 15]

In [75]:
list(filter(lambda num:num%2==0,seq))

[2, 4]

In [77]:
s='suresh kumar maurya'

In [78]:
s.upper()

'SURESH KUMAR MAURYA'

In [79]:
s.split()

['suresh', 'kumar', 'maurya']

In [80]:
tweet='go sports! #sports'

In [81]:
tweet.split('#')

['go sports! ', 'sports']

In [82]:
tweet.split('#')[1]

'sports'

In [85]:
d={'k1':1,'k2':2}

In [86]:
d

{'k1': 1, 'k2': 2}

In [87]:
d.keys()

dict_keys(['k1', 'k2'])

In [88]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [91]:
d.values()

dict_values([1, 2])

In [92]:
lis=[1,2,3,4,5]

In [93]:
item=lis.pop(0)

In [94]:
lis

[2, 3, 4, 5]

In [95]:
'x' in ['x','y','a']

True

In [103]:
x=[(1,2),(3,4),(5,6)]

In [104]:
for ad in x:
    print(ad)

(1, 2)
(3, 4)
(5, 6)


In [106]:
for (a,b) in x:
    print(a)
    print(b)

1
2
3
4
5
6


# - what is 7 to the power of 4 ?

In [107]:
7**4

2401

# - given the varibles:
    

 planet ='earth'
    
    diametr=1234

use .format() to print the following string:

      the diametr of earth is 12742 kilometers.

In [109]:
planet ='earth'
diametr=1234
'  the diametr of earth {} is {} 12742 kilometers:'.format(planet,diametr)

'  the diametr of earth earth is 1234 12742 kilometers:'

# given this nested list use indexing to grab the word 'hello'

In [112]:
list=[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [113]:
list[3]

[5, [100, 200, ['hello']], 23, 11]

In [123]:
list[3][2][1]

TypeError: 'int' object is not subscriptable

In [115]:
list[3][1]

[100, 200, ['hello']]

In [120]:
list[3]

[5, [100, 200, ['hello']], 23, 11]

# create a function that grabs the emal website domain from a string in the form:
      usre@domain.com

In [127]:
def domainGet(email):
    return email.split('@')[1]

In [128]:
domainGet('usre@domain.com')

'domain.com'

In [129]:
def  finddog(s):
    return 'dog' in s.lower().split()

In [130]:
finddog('Is there a dog here?')

True

# create a function that count the number of times the word " dog " occurs in a string . again ignore edge cases.

In [135]:
def countdog(s):
    count=0
    for word in s.lower().split():
        if word =='dog':
            count+=1
    return count

In [137]:
countdog('this dog runs faster than the other dog dude! dog')

3

In [147]:
def caught_speeding(speed, ss):
    
    if ss:
        speeding = speed - 5
    else:
        speeding=speed
    if speeding>80:
        return 'big ticket'
    elif speeding >60:
        return 'small ticket'
    else:
        return 'no ticket'

In [148]:
caught_speeding(81,True)

'small ticket'

In [149]:
caught_speeding(81,False)

'big ticket'

# NUMPY ARRAYS

In [1]:
my_list =[1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
aar=np.array(my_list)

In [5]:
aar

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5)

array([0.32141308, 0.45100942, 0.77653458, 0.36032838, 0.36989536])

In [28]:
np.random.rand(5,5)

array([[0.53179277, 0.93322916, 0.25055774, 0.28290355, 0.4688719 ],
       [0.89675493, 0.28029632, 0.98820206, 0.0750183 , 0.22093832],
       [0.80261732, 0.89717734, 0.43199252, 0.82427097, 0.39044747],
       [0.53156903, 0.04772598, 0.28418746, 0.19579379, 0.20069779],
       [0.74367422, 0.70519275, 0.51866694, 0.29460273, 0.46064896]])

In [29]:
np.random.rand(2)

array([0.97404794, 0.67790347])

In [33]:
np.random.randint(1,50,10)

array([40,  1, 26, 39, 23, 33, 40, 38, 22, 43])

In [34]:
arr=np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.max()

24

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.argmax()

24

In [41]:
arr.argmin()

0

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.shape

(25,)

In [46]:
arr.dtype

dtype('int32')

In [47]:
from numpy.random import randint

In [48]:
randint(2,10)

9

#                           Numpy Indexing and selection

In [49]:
import numpy as np

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [55]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[0:5]=100

In [57]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
arr=np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
slice_of_arr=arr[0:6]

In [61]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [62]:
slice_of_arr[:]=90

In [63]:
slice_of_arr

array([90, 90, 90, 90, 90, 90])

In [64]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [65]:
arr_copy=arr.copy()

In [66]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:]=100

In [68]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [71]:

arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr_2d[1][2]

6

In [80]:
arr_2d[1,1]

5

In [81]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [82]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

conditional operator

In [84]:
arr=np.arange(1,11)

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
bool_arr=arr>5

In [87]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [88]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [89]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [93]:
arr_2d = np.arange(50).reshape(5,10)

In [95]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [98]:
arr_2d[4,9]

49

In [99]:
arr_2d[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [100]:
arr_2d[2][3]

23